% Returns true if two discs don't overlap.
function out = not_overlap_fast(disc1,disc2)
x = disc1(1:2); rx = disc1(3);
y = disc2(1:2); ry = disc2(3);
out = (min([norm(x - y), ...
    norm(x - y + [1,0]), ...
    norm(x - y - [1,0]), ...
    norm(x - y + [0,1]), ...
    norm(x - y - [0,1]), ...
    norm(x - y + [1,1]), ...
    norm(x - y - [1,1]), ...
    norm(x - y + [-1,1]), ...
    norm(x - y - [-1,1])]) <= rx + ry ); 
end

